baseurl = "https://www.chegwin.org/"
languageCode = "en-gb"
theme = "terminal"
paginate = 5
uglyURLs = true

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 5
  fullWidthTheme = true
  centerTheme = false

[languages]
  [languages.en]
    title = "www.chegwin.org"
    copyright = "&copy; 2020"
    [languages.en.params]
      keywords = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/posts/about.html"
      [[languages.en.menu.main]]
        identifier = "Twitter"
        name = "Twitter"
        url = "https://twitter.com/tommybobbins"
      [[languages.en.menu.main]]
        identifier = "GitHub"
        name = "GitHub"
        url = "https://github.com/tommybobbins"
      [[languages.en.menu.main]]
        identifier = "Linux"
        name = "Linux"
        url = "/posts/linux.html"
