name: Upload Website to S3

on:
  push:
    branches:
    - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Read .env
        id: hugo-version
        run: |
          . ./.env
          echo "HUGO_VERSION=${HUGO_VERSION}" >> "${GITHUB_OUTPUT}"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '${{ steps.hugo-version.outputs.HUGO_VERSION }}'
          extended: true

#      - uses: actions/cache@v4
#        with:
#          path: /tmp/hugo_cache_s3
#          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-hugomod-


      - name: Build
        run: |
             cd hugo 
             hugo -D --config config.toml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.ACTIONS_AWS_ROLE }}
          role-session-name: SyncToS3

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./hugo/public/ s3://${{ vars.AWS_WWW_BUCKET_NAME }}/ --delete
        #run: aws s3 ls s3://${{ vars.AWS_WWW_BUCKET_NAME }}/ 

      - name: Clear CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.AWS_CLOUDFRONT_ID }} --paths "/*"
